//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPM.Web.MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPM.Web.MultiLanguage.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account existed.
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account incorrect.
        /// </summary>
        public static string AccountIncorrect {
            get {
                return ResourceManager.GetString("AccountIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer Account.
        /// </summary>
        public static string AccountInterviewer {
            get {
                return ResourceManager.GetString("AccountInterviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required.
        /// </summary>
        public static string AccountRequired {
            get {
                return ResourceManager.GetString("AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add candidate.
        /// </summary>
        public static string AddCandidate {
            get {
                return ResourceManager.GetString("AddCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddCandidateButton {
            get {
                return ResourceManager.GetString("AddCandidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Catalog.
        /// </summary>
        public static string AddCatalog {
            get {
                return ResourceManager.GetString("AddCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Guideline.
        /// </summary>
        public static string AddGuideline {
            get {
                return ResourceManager.GetString("AddGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add interview process failed. Please try againt!.
        /// </summary>
        public static string AddInterviewProcessFailed {
            get {
                return ResourceManager.GetString("AddInterviewProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Catalog.
        /// </summary>
        public static string AddNewCatalog {
            get {
                return ResourceManager.GetString("AddNewCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Question.
        /// </summary>
        public static string AddNewQuestion {
            get {
                return ResourceManager.GetString("AddNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD POSITION.
        /// </summary>
        public static string AddPositionlHeader {
            get {
                return ResourceManager.GetString("AddPositionlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add interview process success.
        /// </summary>
        public static string AddProcessSuccess {
            get {
                return ResourceManager.GetString("AddProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question Fail!.
        /// </summary>
        public static string AddQuestionFail {
            get {
                return ResourceManager.GetString("AddQuestionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SKILL.
        /// </summary>
        public static string AddSkillHeader {
            get {
                return ResourceManager.GetString("AddSkillHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user not success.
        /// </summary>
        public static string AddUserFail {
            get {
                return ResourceManager.GetString("AddUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user success.
        /// </summary>
        public static string AddUserSuccess {
            get {
                return ResourceManager.GetString("AddUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For.
        /// </summary>
        public static string ApplyForGroup {
            get {
                return ResourceManager.GetString("ApplyForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Candidate ?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisCandidate {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Delete This Question?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisQuestion {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign candidates.
        /// </summary>
        public static string AssignCandidates {
            get {
                return ResourceManager.GetString("AssignCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelCandidateButton {
            get {
                return ResourceManager.GetString("CancelCandidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTransmit {
            get {
                return ResourceManager.GetString("CancelTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address exceeds 50 characters.
        /// </summary>
        public static string CandidateAddressLengh {
            get {
                return ResourceManager.GetString("CandidateAddressLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate&apos;s Answer.
        /// </summary>
        public static string CandidateAnswer {
            get {
                return ResourceManager.GetString("CandidateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CandidateEmail {
            get {
                return ResourceManager.GetString("CandidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        public static string CandidateEmailInvalid {
            get {
                return ResourceManager.GetString("CandidateEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email exceeds 50 characters.
        /// </summary>
        public static string CandidateEmailLengh {
            get {
                return ResourceManager.GetString("CandidateEmailLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string CandidateEmailRequired {
            get {
                return ResourceManager.GetString("CandidateEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card has 9 numberics.
        /// </summary>
        public static string CandidateIdCardInvalid {
            get {
                return ResourceManager.GetString("CandidateIdCardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card has must be 9 numberics.
        /// </summary>
        public static string CandidateIdCardLength {
            get {
                return ResourceManager.GetString("CandidateIdCardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string CandidateInformation {
            get {
                return ResourceManager.GetString("CandidateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major exceeds 50 characters.
        /// </summary>
        public static string CandidateMajorLengh {
            get {
                return ResourceManager.GetString("CandidateMajorLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate name.
        /// </summary>
        public static string CandidateName {
            get {
                return ResourceManager.GetString("CandidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name doesn&apos;t contain special characters.
        /// </summary>
        public static string CandidateNameInvalid {
            get {
                return ResourceManager.GetString("CandidateNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name exceeds 50 characters.
        /// </summary>
        public static string CandidateNameLengh {
            get {
                return ResourceManager.GetString("CandidateNameLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        public static string CandidateNameRequired {
            get {
                return ResourceManager.GetString("CandidateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate not found.
        /// </summary>
        public static string CandidateNotFound {
            get {
                return ResourceManager.GetString("CandidateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number has must 10 or 11 numberics.
        /// </summary>
        public static string CandidatePhoneInvalid {
            get {
                return ResourceManager.GetString("CandidatePhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string CandidatePhoneRequired {
            get {
                return ResourceManager.GetString("CandidatePhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is required.
        /// </summary>
        public static string CandidatePositionRequired {
            get {
                return ResourceManager.GetString("CandidatePositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate profile.
        /// </summary>
        public static string CandidateProfile {
            get {
                return ResourceManager.GetString("CandidateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates GST.
        /// </summary>
        public static string CandidatesGST {
            get {
                return ResourceManager.GetString("CandidatesGST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string CandidateSkill {
            get {
                return ResourceManager.GetString("CandidateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill is required.
        /// </summary>
        public static string CandidateSkillRequired {
            get {
                return ResourceManager.GetString("CandidateSkillRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates Management.
        /// </summary>
        public static string CandidatesManagement {
            get {
                return ResourceManager.GetString("CandidatesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University&apos;s name exceeds 50 characters.
        /// </summary>
        public static string CandidateUniversityLengh {
            get {
                return ResourceManager.GetString("CandidateUniversityLengh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is required.
        /// </summary>
        public static string CandidateUniversityRequired {
            get {
                return ResourceManager.GetString("CandidateUniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get candidate profile.
        /// </summary>
        public static string CanNotGetCandidateProfile {
            get {
                return ResourceManager.GetString("CanNotGetCandidateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transmit candidate. Please check again.
        /// </summary>
        public static string CannotTransmit {
            get {
                return ResourceManager.GetString("CannotTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog ID.
        /// </summary>
        public static string CatalogID {
            get {
                return ResourceManager.GetString("CatalogID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Name.
        /// </summary>
        public static string CatalogName {
            get {
                return ResourceManager.GetString("CatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Code is number or alphatbet upper characters and from 1 to 20 characters.
        /// </summary>
        public static string CheckCode {
            get {
                return ResourceManager.GetString("CheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Name is not special characters.
        /// </summary>
        public static string CheckName {
            get {
                return ResourceManager.GetString("CheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose position.
        /// </summary>
        public static string ChooseResult {
            get {
                return ResourceManager.GetString("ChooseResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Room.
        /// </summary>
        public static string ChooseRoom {
            get {
                return ResourceManager.GetString("ChooseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code or name is exist.
        /// </summary>
        public static string CodeExist {
            get {
                return ResourceManager.GetString("CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coincidence status.
        /// </summary>
        public static string CoincidenceStatus {
            get {
                return ResourceManager.GetString("CoincidenceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Candidate.
        /// </summary>
        public static string CreateCandidate {
            get {
                return ResourceManager.GetString("CreateCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Catalog Fails!.
        /// </summary>
        public static string CreateCatalogFails {
            get {
                return ResourceManager.GetString("CreateCatalogFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Catalog Success!.
        /// </summary>
        public static string CreateCatalogSuccess {
            get {
                return ResourceManager.GetString("CreateCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! When you add new position..
        /// </summary>
        public static string CreateErPo {
            get {
                return ResourceManager.GetString("CreateErPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Guideline Fails!.
        /// </summary>
        public static string CreateGuidelineFails {
            get {
                return ResourceManager.GetString("CreateGuidelineFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Guideline Success!.
        /// </summary>
        public static string CreateGuidelineSuccess {
            get {
                return ResourceManager.GetString("CreateGuidelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interview Process.
        /// </summary>
        public static string CreateInterviewProcess {
            get {
                return ResourceManager.GetString("CreateInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interview Round failed !!!.
        /// </summary>
        public static string CreateInterviewRoundFail {
            get {
                return ResourceManager.GetString("CreateInterviewRoundFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create InterviewRound successful !!!.
        /// </summary>
        public static string CreateInterviewRoundSuccess {
            get {
                return ResourceManager.GetString("CreateInterviewRoundSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Position.
        /// </summary>
        public static string CreatePosition {
            get {
                return ResourceManager.GetString("CreatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Question Fails!.
        /// </summary>
        public static string CreateQuestionFails {
            get {
                return ResourceManager.GetString("CreateQuestionFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Question Success!.
        /// </summary>
        public static string CreateQuestionSuccess {
            get {
                return ResourceManager.GetString("CreateQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interview Round.
        /// </summary>
        public static string CreateRound {
            get {
                return ResourceManager.GetString("CreateRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skill.
        /// </summary>
        public static string CreateSkill {
            get {
                return ResourceManager.GetString("CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create skill failed.
        /// </summary>
        public static string CreateSkillFailed {
            get {
                return ResourceManager.GetString("CreateSkillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create skill success!.
        /// </summary>
        public static string CreateSkillSuccess {
            get {
                return ResourceManager.GetString("CreateSkillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! You add new position successfully..
        /// </summary>
        public static string CreateSuPo {
            get {
                return ResourceManager.GetString("CreateSuPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is Null.
        /// </summary>
        public static string DataIsNull {
            get {
                return ResourceManager.GetString("DataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is unvalid.
        /// </summary>
        public static string DataUnvalid {
            get {
                return ResourceManager.GetString("DataUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Candidate Fail!!!.
        /// </summary>
        public static string DeleteCandidateFail {
            get {
                return ResourceManager.GetString("DeleteCandidateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Candidate Successful!!!.
        /// </summary>
        public static string DeleteCandidateSuccessful {
            get {
                return ResourceManager.GetString("DeleteCandidateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! You delete not successfully..
        /// </summary>
        public static string DeleteErPo {
            get {
                return ResourceManager.GetString("DeleteErPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Interview Round failed !!!.
        /// </summary>
        public static string DeleteInterviewRoundFail {
            get {
                return ResourceManager.GetString("DeleteInterviewRoundFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Interview Round successfu l!!!.
        /// </summary>
        public static string DeleteInterviewRoundSuccess {
            get {
                return ResourceManager.GetString("DeleteInterviewRoundSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Question.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Interview Round.
        /// </summary>
        public static string DeleteRound {
            get {
                return ResourceManager.GetString("DeleteRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Skill.
        /// </summary>
        public static string DeleteSkill {
            get {
                return ResourceManager.GetString("DeleteSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete skill failed.
        /// </summary>
        public static string DeleteSkillFailed {
            get {
                return ResourceManager.GetString("DeleteSkillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete skill success.
        /// </summary>
        public static string DeleteSkillSuccess {
            get {
                return ResourceManager.GetString("DeleteSkillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! You delete position succesfully..
        /// </summary>
        public static string DeleteSuPo {
            get {
                return ResourceManager.GetString("DeleteSuPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Catalog.
        /// </summary>
        public static string DetailCatalog {
            get {
                return ResourceManager.GetString("DetailCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Guideline.
        /// </summary>
        public static string DetailGuideline {
            get {
                return ResourceManager.GetString("DetailGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Interview Process.
        /// </summary>
        public static string DetailInterviewProcess {
            get {
                return ResourceManager.GetString("DetailInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load detail interview process page failed. Please try againt!.
        /// </summary>
        public static string DetailInterviewProcessPageLoadFailed {
            get {
                return ResourceManager.GetString("DetailInterviewProcessPageLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load detail interview round page failed. Please try againt!.
        /// </summary>
        public static string DetailInterviewRoundPageLoadFailed {
            get {
                return ResourceManager.GetString("DetailInterviewRoundPageLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Question.
        /// </summary>
        public static string DetailQuestion {
            get {
                return ResourceManager.GetString("DetailQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Interview Round.
        /// </summary>
        public static string DetailRound {
            get {
                return ResourceManager.GetString("DetailRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detele Guideline Fails!.
        /// </summary>
        public static string DeteleGuidelineFails {
            get {
                return ResourceManager.GetString("DeteleGuidelineFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detele Guideline Success!.
        /// </summary>
        public static string DeteleGuidelineSuccess {
            get {
                return ResourceManager.GetString("DeteleGuidelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detele Question Fails!.
        /// </summary>
        public static string DeteleQuestionFails {
            get {
                return ResourceManager.GetString("DeteleQuestionFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detele Question Success!.
        /// </summary>
        public static string DeteleQuestionSuccess {
            get {
                return ResourceManager.GetString("DeteleQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detete Catalog Fails!.
        /// </summary>
        public static string DeteteCatalogFails {
            get {
                return ResourceManager.GetString("DeteteCatalogFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detete Catalog Success!.
        /// </summary>
        public static string DeteteCatalogSuccess {
            get {
                return ResourceManager.GetString("DeteteCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditCandidate {
            get {
                return ResourceManager.GetString("EditCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Catalog.
        /// </summary>
        public static string EditCatalog {
            get {
                return ResourceManager.GetString("EditCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! When you update position information..
        /// </summary>
        public static string EditErPo {
            get {
                return ResourceManager.GetString("EditErPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Guideline.
        /// </summary>
        public static string EditGuideline {
            get {
                return ResourceManager.GetString("EditGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Interview Process.
        /// </summary>
        public static string EditInterviewProcess {
            get {
                return ResourceManager.GetString("EditInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit interview process failed. Please try againt!.
        /// </summary>
        public static string EditInterviewProcessFailed {
            get {
                return ResourceManager.GetString("EditInterviewProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Interview Result.
        /// </summary>
        public static string EditInterviewResult {
            get {
                return ResourceManager.GetString("EditInterviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Interview Round failed !!!.
        /// </summary>
        public static string EditInterviewRoundFail {
            get {
                return ResourceManager.GetString("EditInterviewRoundFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Interview Round successful !!!.
        /// </summary>
        public static string EditInterviewRoundSuccess {
            get {
                return ResourceManager.GetString("EditInterviewRoundSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT POSITION.
        /// </summary>
        public static string EditPositionHeader {
            get {
                return ResourceManager.GetString("EditPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit interview process success.
        /// </summary>
        public static string EditProcessSuccess {
            get {
                return ResourceManager.GetString("EditProcessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Interview Round.
        /// </summary>
        public static string EditRound {
            get {
                return ResourceManager.GetString("EditRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Skill.
        /// </summary>
        public static string EditSkill {
            get {
                return ResourceManager.GetString("EditSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SKILL.
        /// </summary>
        public static string EditSkillHeader {
            get {
                return ResourceManager.GetString("EditSkillHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! You update position successfully..
        /// </summary>
        public static string EditSuPo {
            get {
                return ResourceManager.GetString("EditSuPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Content.
        /// </summary>
        public static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account.
        /// </summary>
        public static string EnterAccount {
            get {
                return ResourceManager.GetString("EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter role.
        /// </summary>
        public static string EnterRole {
            get {
                return ResourceManager.GetString("EnterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create candidate..
        /// </summary>
        public static string ErrorCandidateCreateFail {
            get {
                return ResourceManager.GetString("ErrorCandidateCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create candidate, save file failed..
        /// </summary>
        public static string ErrorCandidateCreateUploadFail {
            get {
                return ResourceManager.GetString("ErrorCandidateCreateUploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get candidate profile..
        /// </summary>
        public static string ErrorCandidateLoadProfileFail {
            get {
                return ResourceManager.GetString("ErrorCandidateLoadProfileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save candidate profile..
        /// </summary>
        public static string ErrorCandidateSaveProfileFail {
            get {
                return ResourceManager.GetString("ErrorCandidateSaveProfileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in at least one input to filter data.
        /// </summary>
        public static string ErrorFillReport {
            get {
                return ResourceManager.GetString("ErrorFillReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Name is exist !.
        /// </summary>
        public static string ErrorNameExistSkill {
            get {
                return ResourceManager.GetString("ErrorNameExistSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Interview Answer For Empty Interview Fail!.
        /// </summary>
        public static string GenerateInterviewAnswerFail {
            get {
                return ResourceManager.GetString("GenerateInterviewAnswerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Interview Info Fail!.
        /// </summary>
        public static string GetInterviewInfoFail {
            get {
                return ResourceManager.GetString("GetInterviewInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string GPA {
            get {
                return ResourceManager.GetString("GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guideline ID.
        /// </summary>
        public static string GuidelineID {
            get {
                return ResourceManager.GetString("GuidelineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Interview Management.
        /// </summary>
        public static string GuidelineInterviewManagement {
            get {
                return ResourceManager.GetString("GuidelineInterviewManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guideline Name.
        /// </summary>
        public static string GuidelineName {
            get {
                return ResourceManager.GetString("GuidelineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string IdCard {
            get {
                return ResourceManager.GetString("IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID must be positive.
        /// </summary>
        public static string IDPositive {
            get {
                return ResourceManager.GetString("IDPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information assign.
        /// </summary>
        public static string InformationAssign {
            get {
                return ResourceManager.GetString("InformationAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information interview process.
        /// </summary>
        public static string InformationInterviewProcess {
            get {
                return ResourceManager.GetString("InformationInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview management.
        /// </summary>
        public static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Admin.
        /// </summary>
        public static string InterviewAdmin {
            get {
                return ResourceManager.GetString("InterviewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer.
        /// </summary>
        public static string Interviewer {
            get {
                return ResourceManager.GetString("Interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer Management.
        /// </summary>
        public static string InterviewerManagement {
            get {
                return ResourceManager.GetString("InterviewerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewers.
        /// </summary>
        public static string Interviewers {
            get {
                return ResourceManager.GetString("Interviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview History.
        /// </summary>
        public static string InterviewHistory {
            get {
                return ResourceManager.GetString("InterviewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Info.
        /// </summary>
        public static string InterviewInfo {
            get {
                return ResourceManager.GetString("InterviewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterviewProcess.
        /// </summary>
        public static string InterviewProcess {
            get {
                return ResourceManager.GetString("InterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Process name can not exceed 100 characters.
        /// </summary>
        public static string InterviewProcessNameTooLong {
            get {
                return ResourceManager.GetString("InterviewProcessNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview process is not found..
        /// </summary>
        public static string InterviewProcessNotFound {
            get {
                return ResourceManager.GetString("InterviewProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview process can not null!.
        /// </summary>
        public static string InterviewProcessNull {
            get {
                return ResourceManager.GetString("InterviewProcessNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Process start date can not exceed 10 characters.
        /// </summary>
        public static string InterviewProcessStartDateTooLong {
            get {
                return ResourceManager.GetString("InterviewProcessStartDateTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Result.
        /// </summary>
        public static string InterviewResult {
            get {
                return ResourceManager.GetString("InterviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Results.
        /// </summary>
        public static string InterviewResults {
            get {
                return ResourceManager.GetString("InterviewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Results Management.
        /// </summary>
        public static string InterviewResultsManagement {
            get {
                return ResourceManager.GetString("InterviewResultsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Round.
        /// </summary>
        public static string InterviewRound {
            get {
                return ResourceManager.GetString("InterviewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterviewRound not found !!!.
        /// </summary>
        public static string InterviewRoundNotFound {
            get {
                return ResourceManager.GetString("InterviewRoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview Schedule.
        /// </summary>
        public static string InterviewSchedule {
            get {
                return ResourceManager.GetString("InterviewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System IPM.
        /// </summary>
        public static string IPM {
            get {
                return ResourceManager.GetString("IPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List candidate.
        /// </summary>
        public static string ListCandidate {
            get {
                return ResourceManager.GetString("ListCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Catalog.
        /// </summary>
        public static string ListCatalog {
            get {
                return ResourceManager.GetString("ListCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Catalog In Guideline.
        /// </summary>
        public static string ListCatalogInGuideline {
            get {
                return ResourceManager.GetString("ListCatalogInGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Guideline.
        /// </summary>
        public static string ListGuideline {
            get {
                return ResourceManager.GetString("ListGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List interview admin.
        /// </summary>
        public static string ListInterviewAdmin {
            get {
                return ResourceManager.GetString("ListInterviewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Interview Process.
        /// </summary>
        public static string ListInterviewProcess {
            get {
                return ResourceManager.GetString("ListInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Position.
        /// </summary>
        public static string ListPositions {
            get {
                return ResourceManager.GetString("ListPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List questions.
        /// </summary>
        public static string ListQuestion {
            get {
                return ResourceManager.GetString("ListQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Interview Round.
        /// </summary>
        public static string ListRounds {
            get {
                return ResourceManager.GetString("ListRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Skill.
        /// </summary>
        public static string ListSkills {
            get {
                return ResourceManager.GetString("ListSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List User.
        /// </summary>
        public static string ListUser {
            get {
                return ResourceManager.GetString("ListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Candidate Is Fail.
        /// </summary>
        public static string LoadCandidateIsFail {
            get {
                return ResourceManager.GetString("LoadCandidateIsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Catalog Fails!.
        /// </summary>
        public static string LoadCatalogFails {
            get {
                return ResourceManager.GetString("LoadCatalogFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Catalog Success!.
        /// </summary>
        public static string LoadCatalogSuccess {
            get {
                return ResourceManager.GetString("LoadCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Guideline Fails!.
        /// </summary>
        public static string LoadGuidelineFails {
            get {
                return ResourceManager.GetString("LoadGuidelineFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Guideline Success!.
        /// </summary>
        public static string LoadGuidelineSuccess {
            get {
                return ResourceManager.GetString("LoadGuidelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data.
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Interview Fail!.
        /// </summary>
        public static string LoadInterviewFail {
            get {
                return ResourceManager.GetString("LoadInterviewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Interview Results Fail!.
        /// </summary>
        public static string LoadInterviewResultsFail {
            get {
                return ResourceManager.GetString("LoadInterviewResultsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Interview Schedule Fail!.
        /// </summary>
        public static string LoadInterviewScheduleFail {
            get {
                return ResourceManager.GetString("LoadInterviewScheduleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Question Fails!.
        /// </summary>
        public static string LoadQuestionFails {
            get {
                return ResourceManager.GetString("LoadQuestionFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Question Success!.
        /// </summary>
        public static string LoadQuestionSuccess {
            get {
                return ResourceManager.GetString("LoadQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Calendar.
        /// </summary>
        public static string ManagementCalendar {
            get {
                return ResourceManager.GetString("ManagementCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Management.
        /// </summary>
        public static string ManagementCandidate {
            get {
                return ResourceManager.GetString("ManagementCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Catalog.
        /// </summary>
        public static string ManagementCatalog {
            get {
                return ResourceManager.GetString("ManagementCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Guideline.
        /// </summary>
        public static string ManagementGuideline {
            get {
                return ResourceManager.GetString("ManagementGuideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Interview Admin.
        /// </summary>
        public static string ManagementInterviewAdmin {
            get {
                return ResourceManager.GetString("ManagementInterviewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Interview Process.
        /// </summary>
        public static string ManagementInterviewProcess {
            get {
                return ResourceManager.GetString("ManagementInterviewProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maganement Interview Round.
        /// </summary>
        public static string ManagementInterviewRound {
            get {
                return ResourceManager.GetString("ManagementInterviewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Questions.
        /// </summary>
        public static string ManagementQuestions {
            get {
                return ResourceManager.GetString("ManagementQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Skill.
        /// </summary>
        public static string ManagementSkills {
            get {
                return ResourceManager.GetString("ManagementSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management User.
        /// </summary>
        public static string ManagementUser {
            get {
                return ResourceManager.GetString("ManagementUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Position.
        /// </summary>
        public static string ManagePositions {
            get {
                return ResourceManager.GetString("ManagePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Point.
        /// </summary>
        public static string MaxPoint {
            get {
                return ResourceManager.GetString("MaxPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Request.
        /// </summary>
        public static string MeetingRequest {
            get {
                return ResourceManager.GetString("MeetingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code or name is existed..
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer Name.
        /// </summary>
        public static string NameInterviewer {
            get {
                return ResourceManager.GetString("NameInterviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 10 and  20.
        /// </summary>
        public static string NameRange {
            get {
                return ResourceManager.GetString("NameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Duplication.
        /// </summary>
        public static string NoDuplication {
            get {
                return ResourceManager.GetString("NoDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not supported yet.
        /// </summary>
        public static string NotSupportedFunction {
            get {
                return ResourceManager.GetString("NotSupportedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumOfCandidate.
        /// </summary>
        public static string NumOfCandidate {
            get {
                return ResourceManager.GetString("NumOfCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must not be null.
        /// </summary>
        public static string ObjectNotNull {
            get {
                return ResourceManager.GetString("ObjectNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherInfo {
            get {
                return ResourceManager.GetString("OtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass/Fail/NonePassFail.
        /// </summary>
        public static string PassFail {
            get {
                return ResourceManager.GetString("PassFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be Pass or Fail!.
        /// </summary>
        public static string PassOrFail {
            get {
                return ResourceManager.GetString("PassOrFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Name.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process list round can not empty.
        /// </summary>
        public static string ProcessListRoundNotEmpty {
            get {
                return ResourceManager.GetString("ProcessListRoundNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name can not empty.
        /// </summary>
        public static string ProcessNameNotEmpty {
            get {
                return ResourceManager.GetString("ProcessNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process start date can not empty.
        /// </summary>
        public static string ProcessStartDateNotEmpty {
            get {
                return ResourceManager.GetString("ProcessStartDateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Name.
        /// </summary>
        public static string QuestionName {
            get {
                return ResourceManager.GetString("QuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Candidates.
        /// </summary>
        public static string ReportCandidates {
            get {
                return ResourceManager.GetString("ReportCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Candidates GST.
        /// </summary>
        public static string ReportCandidatesGst {
            get {
                return ResourceManager.GetString("ReportCandidatesGst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Skill And Careers.
        /// </summary>
        public static string ReportSkillAndCareers {
            get {
                return ResourceManager.GetString("ReportSkillAndCareers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetCandidateButton {
            get {
                return ResourceManager.GetString("ResetCandidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not choose.
        /// </summary>
        public static string RoleNotChoose {
            get {
                return ResourceManager.GetString("RoleNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 1.
        /// </summary>
        public static string Round1 {
            get {
                return ResourceManager.GetString("Round1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 2.
        /// </summary>
        public static string Round2 {
            get {
                return ResourceManager.GetString("Round2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 3.
        /// </summary>
        public static string Round3 {
            get {
                return ResourceManager.GetString("Round3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Name.
        /// </summary>
        public static string RoundName {
            get {
                return ResourceManager.GetString("RoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCandidateButton {
            get {
                return ResourceManager.GetString("SaveCandidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transmit candidate. Please select other interview admin.
        /// </summary>
        public static string SelectOtherInterviewAdmin {
            get {
                return ResourceManager.GetString("SelectOtherInterviewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Answer or Comment Fail!.
        /// </summary>
        public static string SetAswerorCommentFail {
            get {
                return ResourceManager.GetString("SetAswerorCommentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Catalog Mark Fail!.
        /// </summary>
        public static string SetCatalogMarkFail {
            get {
                return ResourceManager.GetString("SetCatalogMarkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Result Fail!.
        /// </summary>
        public static string SetResultFail {
            get {
                return ResourceManager.GetString("SetResultFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        public static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill name is required.
        /// </summary>
        public static string SkillNameRequired {
            get {
                return ResourceManager.GetString("SkillNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is unvalid.
        /// </summary>
        public static string SkillNameUnvalid {
            get {
                return ResourceManager.GetString("SkillNameUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills/Certificates.
        /// </summary>
        public static string SkillsGroup {
            get {
                return ResourceManager.GetString("SkillsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillsLabel {
            get {
                return ResourceManager.GetString("SkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add candidate successfully!.
        /// </summary>
        public static string SuccessCandidateCreate {
            get {
                return ResourceManager.GetString("SuccessCandidateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update candidate successfully!.
        /// </summary>
        public static string SuccessCandidateUpdate {
            get {
                return ResourceManager.GetString("SuccessCandidateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is maintenance. Please contact the administrator.
        /// </summary>
        public static string SystemMaintain {
            get {
                return ResourceManager.GetString("SystemMaintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Interviewers.
        /// </summary>
        public static string ToInterviewers {
            get {
                return ResourceManager.GetString("ToInterviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit.
        /// </summary>
        public static string Transmit {
            get {
                return ResourceManager.GetString("Transmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit candidate.
        /// </summary>
        public static string TransmitCandidate {
            get {
                return ResourceManager.GetString("TransmitCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit candidate fail.
        /// </summary>
        public static string TransmitFail {
            get {
                return ResourceManager.GetString("TransmitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit candidate successful!!!.
        /// </summary>
        public static string TransmitSucess {
            get {
                return ResourceManager.GetString("TransmitSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Catalog Fails!.
        /// </summary>
        public static string UpdateCatalogFails {
            get {
                return ResourceManager.GetString("UpdateCatalogFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Catalog Success!.
        /// </summary>
        public static string UpdateCatalogSuccess {
            get {
                return ResourceManager.GetString("UpdateCatalogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Guideline Fails!.
        /// </summary>
        public static string UpdateGuidelineFails {
            get {
                return ResourceManager.GetString("UpdateGuidelineFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Guideline Success!.
        /// </summary>
        public static string UpdateGuidelineSuccess {
            get {
                return ResourceManager.GetString("UpdateGuidelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Question Fails!.
        /// </summary>
        public static string UpdateQuestionFails {
            get {
                return ResourceManager.GetString("UpdateQuestionFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Question Success!.
        /// </summary>
        public static string UpdateQuestionSuccess {
            get {
                return ResourceManager.GetString("UpdateQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateSkill {
            get {
                return ResourceManager.GetString("UpdateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update skill failed.
        /// </summary>
        public static string UpdateSkillFailed {
            get {
                return ResourceManager.GetString("UpdateSkillFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update skill success.
        /// </summary>
        public static string UpdateSkillSuccess {
            get {
                return ResourceManager.GetString("UpdateSkillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user not sussess.
        /// </summary>
        public static string UpdateUserFail {
            get {
                return ResourceManager.GetString("UpdateUserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updae user not success.
        /// </summary>
        public static string UpdateUserSuccess {
            get {
                return ResourceManager.GetString("UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string UploadFileBrowser {
            get {
                return ResourceManager.GetString("UploadFileBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFileLabel {
            get {
                return ResourceManager.GetString("UploadFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View candidate.
        /// </summary>
        public static string ViewCandidate {
            get {
                return ResourceManager.GetString("ViewCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete it ?.
        /// </summary>
        public static string WarningDelete {
            get {
                return ResourceManager.GetString("WarningDelete", resourceCulture);
            }
        }
    }
}
